blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'),
    # 글 상세 조회
    path("<int:pk>/", views.DetailView.as_view(), name='detail'),
    # 글 작성
    path("write/", views.Write.as_view(), name='write'),
    # 글 수정
    path("edit/<int:pk>/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("delete/<int:pk>/", views.Delete.as_view(), name='delete'),
    # 검색
    path("search/<str:tag>/", views.Search.as_view(), name='search'),
]

djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.IndexMain.as_view()),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30, null=False)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, blank=True, default='Null')

    def __str__(self) -> str:
        return f'num:{str(self.pk)}, title:{self.title} {self.writer.email}'


class Category(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self) -> str:
        return self.name
    

class Hashtag(models.Model):
    name = models.CharField(max_length=50)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name
    

class Photo(models.Model):
    filePath = models.CharField(max_length=255)
    originName = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'post: {self.post.pk}, {self.post.title}, fileName: {self.originName}'
    

class Comment(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    parent_id = models.IntegerField(null=False, default=0)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'post: {self.post.pk}, {self.post.title}, fileName: {self.writer.email}'

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content', 'category']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from .models import Post, Category
from .forms import PostForm
import math


categorys = Category.objects.all()
### Post
class Index(View):

    def get(self, request):
        per_page = 10
        page = request.GET.get('page', '1')
        posts = Post.objects.order_by('-created_at')
        paginator = Paginator(posts, per_page)
        lastPage = math.ceil(paginator.count/per_page)
        if(int(page) > lastPage):
            page = '1'
        page_obj = paginator.get_page(page)
        range_start = (int(page)-1)//5*5+1
        page_range = range(range_start,range_start+5 if range_start+4 < lastPage else (lastPage+1 if lastPage > 1 else 2))
        context = {
            "title": "Blog",
            "posts": page_obj,
            "lastPage": lastPage,
            "pageRange": page_range,
            "categorys": categorys,
        }
        return render(request, 'blog/post_list.html', context)
    
class DetailView(View):

    def get(self, request, pk):
        try:
            post = Post.objects.get(pk=pk)
        except ObjectDoesNotExist as e:
            return render(request, 'blog/post_404.html')
        # except:
        #     return redirect('blog:list')
        context = {
            "post": post,
        }
        return render(request, 'blog/post_detail.html', context)
    

class Write(LoginRequiredMixin, View):

    def get(self, request):
        categorys = Category.objects.all()
        context = {
            'categorys': categorys,
            "title": "글쓰기"
        }
        return render(request, 'blog/post_form.html', context)
    
    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():    
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            return redirect('blog:list')
        categorys = Category.objects.all()
        context = {
            "title": "글쓰기",
            'form': form,
            'categorys': categorys,
        }
        return render(request, 'blog/post_form.html', context)
    

class Update(LoginRequiredMixin, View):

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        categorys = Category.objects.all()
        context = {
            "title": "글 수정",
            'post': post,
            'categorys': categorys,
        }
        
        return render(request, 'blog/post_edit.html', context)
    
    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(request.POST)
        if form.is_valid():    
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.category = form.cleaned_data['category']
            post.save()
            return redirect('blog:list')
        categorys = Category.objects.all()
        context = {
            "title": "글 수정",
            'form': form,
            'categorys': categorys,
        }
        return render(request, 'blog/post_edit.html', context)
    

class Delete(View):
    
    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        return redirect('blog:list')
    

class Search(View):

    def get(self, request, tag):
        per_page = 10
        page = request.GET.get('page', '1')
        tags = tag.split('&')
        FILTER = {}
        if tags[0]:
            FILTER["category"] = int(tags[0])
        if tags[1]:
            FILTER["title__contains"] = tags[1]
        posts = Post.objects.filter(**FILTER).order_by('-created_at')
        paginator = Paginator(posts, per_page)
        lastPage = math.ceil(paginator.count/per_page)
        if(int(page) > lastPage):
            page = '1'
        page_obj = paginator.get_page(page)
        range_start = (int(page)-1)//5*5+1
        page_range = range(range_start,range_start+5 if range_start+4 < lastPage else (lastPage+1 if lastPage > 1 else 2))
        context = {
            "title": "Blog",
            "posts": page_obj,
            "lastPage": math.ceil(page_obj.paginator.count/per_page),
            "pageRange": page_range,
            "categorys": categorys
        }
        return render(request, 'blog/post_list.html', context)

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}

{% block content %}
    <h2 class="main-title">게시판</h2>

    <div class="board-top">
      <p class="main-desc"><strong>2개</strong>의 게시글이 있습니다.</p>

      <div>
        <label for="category" class="a11y-hidden">카테고리</label>
        <select id="category">
          <option>전체</option>
          <option>공지사항</option>
          <option>일반</option>
        </select>
        <form class="search-form">
          <label for="search" class="a11y-hidden">검색</label>
          <input id="search" type="search" placeholder="검색어를 입력해주세요">
          <button type="submit">
            <img src="{% static 'img/icon-search.png' %}" alt="검색">
          </button>
        </form>

        <label for="sort" class="a11y-hidden">정렬</label>
        <select id="sort">
          <option>조회순</option>
          <option>최신순</option>
        </select>
      </div>
    </div>


    <!-- 게시판 리스트 -->
    <table class="table list">
      <colgroup>
        <col style="width: 40px">
        <col style="width: 60px">
        <col>
        <col style="width: 100px">
        <col style="width: 120px">
        <col style="width: 100px">
      </colgroup>
      <thead>
        <tr>
          <th>
            <input type="checkbox" id="all-article">
            <!-- <label for="all-article">페이지 전체 게시글 선택</label> -->
          </th>
          <th>번호</th>
          <th>제목</th>
          <th>작성자</th>
          <th>작성일</th>
          <th>조회수</th>
        </tr>
      </thead>
      <tbody>
        <!-- 게시글이 없을때 / 검색한 게시글이 없을때 -->
        <!-- <tr>
            <td class="nodata" colspan="5">등록된 게시물이 없습니다.</td>
          </tr> -->
        <!-- 게시글이 있을때 -->
        {%for post in posts %}
        <tr>
          <td>
            <input type="checkbox" id="check2">
            <!-- <label for="check1">2번 게시글</label> -->
          </td>
          <td>{{ post.id }}</td>
          <td>
            <a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a>
          </td>
          <td>홍길동</td>
          <td>{{ post.created_at }}</td>
          <td>999</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <!-- //게시판 리스트 -->


    <div class="board-bottom">
      <!-- 페이지 -->
      <div class="pagination">
        <a href="#"><img src="{% static 'img/first.png' %}" alt="첫번째 페이지"></a>
        <a href="#"><img src="{% static 'img/prev.png' %}" alt="이전 페이지"></a>
        <a href="#" class="num active">1</a>
        <a href="#" class="num">2</a>
        <a href="#" class="num">3</a>
        <a href="#" class="num">4</a>
        <a href="#" class="num">5</a>
        <a href="#"><img src="{% static 'img/next.png' %}" alt="다음 페이지"></a>
        <a href="#"><img src="{% static 'img/last.png' %}" alt="마지막 페이지"></a>
      </div>
      <!-- //페이지 -->
      <div class="btn-group">
        <button class="btn">선택삭제</button>
        <a href="./write.html" class="btn">글쓰기</a>
      </div>
    </div>
{% endblock %}

blog/templates/blog/post_404.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/view.css' %}">
{% endblock %}

{% block content %}
  <h2 class="main-title">존재하지 않는 게시글입니다.</h2>
  <a href="{% url 'blog:list' %}" class="btn">목록 보기</a>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/view.css' %}">
{% endblock %}

{% block content %}
<h2 class="main-title">글 조회</h2>


<div class="view">
  <div class="view-header">
    <h2>{{ post.title }}</h2>
    <div class="view-info">
      {% if post.category.name != Null %}
      <p>카테고리: {{ post.category.name }}</p>|
      {% endif %}
      <p>작성자: {{ post.writer.email }}</p>|
      <p>작성일: {{ post.created_at | date:'Y-m-d H:i'}}</p>|
      <p>조회수: {{ post.views }}</p>
    </div>
  </div>
  <div class="view-content">
    {{ post.content }}
  </div>
</div>
<div class="btn-group">
  <a href="{% url 'blog:list' %}" class="btn">목록</a>
  {% if post.writer == request.user %}
    <a href="{% url 'blog:edit' pk=post.id %}" class="btn">수정</a>
    <form action="{% url 'blog:delete' pk=post.id %}" method="post" class="delete-btn">
      {% csrf_token %}
      <input type="submit" value="삭제" class="btn">
    </form>
  {% endif %}
</div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="{% static 'css/write.css' %}">
{% endblock %}

{% block content %}
<!-- 글쓰기 페이지 -->
<h2 class="main-title">글쓰기</h2>
<p class="main-desc">내용을 입력 해주세요.</p>

<form action="{% url 'blog:edit' pk=post.id %}" method="post">
  {% csrf_token %}
  <table class="table write">
    <colgroup>
      <col style="width: 120px">
      <col>
    </colgroup>
    <tbody>
      <tr>
        <th><label for="category">카테고리</label></th>
        <td>
          <select id="category" name="category">
            <option value="" {% if post.category.id == Null%}selected{% endif %} hidden>선택</option>
            {% for category in categorys %}
              <option value="{{ category.id }}" {% if category.id == post.category.id%}selected{%endif%}>{{category.name}}</option>
            {% endfor %}
          </select>
        </td>
      </tr>
      <tr>
        <th><label for="title">제목</label></th>
        <td><input type="text" id="title" name="title" value="{{ post.title }}"></td>
      </tr>
      <tr>
        <th><label for="content">내용</label></th>
        <td>
          <textarea id="content" name="content">{{ post.title }}</textarea>
        </td>
      </tr>
          <tr>
            <th><label for="board-file">파일첨부</label></th>
            <td>
              <input type="file" id="board-file">
            </td>
          </tr>
        </tbody>
      </table>
      <div class="btn-group">
        <a href="{% url 'blog:list' %}" class="btn">목록</a>
        <button type="reset" class="btn">초기화</button>
        <button type="submit" class="btn">수정</button>
      </div>
    </form>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link rel="stylesheet" href="{% static 'css/write.css' %}">
{% endblock %}

{% block content %}
<!-- 글쓰기 페이지 -->
<h2 class="main-title">글쓰기</h2>
<p class="main-desc">내용을 입력 해주세요.</p>

<form action="{% url 'blog:write' %}" method="post">
  {% csrf_token %}
  <table class="table write">
    <colgroup>
      <col style="width: 120px">
      <col>
    </colgroup>
    <tbody>
      <tr>
        <th><label for="category">카테고리</label></th>
        <td>
          <select id="category" name="category">
            <option value="" selected hidden>선택</option>
            {% for category in categorys %}
              <option value="{{ category.id }}">{{category.name}}</option>
            {% endfor %}
          </select>
        </td>
      </tr>
      <tr>
        <th><label for="title">제목</label></th>
        <td><input type="text" id="title" name="title"></td>
      </tr>
      <tr>
        <th><label for="content">내용</label></th>
        <td>
          <textarea id="content" name="content"></textarea>
        </td>
      </tr>
          <tr>
            <th><label for="board-file">파일첨부</label></th>
            <td>
              <input type="file" id="board-file">
            </td>
          </tr>
        </tbody>
      </table>
      <div class="btn-group">
        <a href="{% url 'blog:list' %}" class="btn">목록</a>
        <button type="reset" class="btn">초기화</button>
        <button type="submit" class="btn">작성</button>
      </div>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
  <link rel="stylesheet" href="{% static 'css/table.css' %}">
  <link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}

{% block content %}
  <h2 class="main-title">게시판</h2>

  <div class="board-top">
    <p class="main-desc"><strong>{{ posts.paginator.count }}개</strong>의 게시글이 있습니다.</p>

    <div>
      <form id="search-form" class="search-form">
        <label for="category" class="a11y-hidden">카테고리</label>
        <select id="category" name="category">
          <option value="" selected hidden>선택</option>
          {% for category in categorys %}
            <option value="{{ category.id }}">{{category.name}}</option>
          {% endfor %}
        </select>
        <label for="search" class="a11y-hidden">검색</label>
        <input id="search" type="search" name="search" placeholder="검색어를 입력해주세요" vlaue=" ">
        <button type="submit">
          <img src="{% static 'img/icon-search.png' %}" alt="검색">
        </button>
      </form>

      <label for="sort" class="a11y-hidden">정렬</label>
      <select id="sort">
        <option>조회순</option>
        <option>최신순</option>
      </select>
    </div>
  </div>


  <!-- 게시판 리스트 -->
  <table class="table list">
    <colgroup>
      <!-- <col style="width: 40px"> -->
      <col style="width: 60px">
      <col style="width: 140px">
      <col>
      <col style="width: 150px">
      <col style="width: 120px">
      <col style="width: 100px">
    </colgroup>
    <thead>
      <tr>
        <!-- <th>
          <input type="checkbox" id="all-article">
          <label for="all-article">페이지 전체 게시글 선택</label>
        </th> -->
        <th>번호</th>
        <th>카테고리</th>
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
        <th>조회수</th>
      </tr>
    </thead>
    <tbody>
      <!-- 게시글이 없을때 / 검색한 게시글이 없을때 -->
      <!-- <tr>
          <td class="nodata" colspan="5">등록된 게시물이 없습니다.</td>
        </tr> -->
      <!-- 게시글이 있을때 -->
      {%for post in posts %}
        <tr>
          <!-- <td>
            <input type="checkbox" id="check2">
            <label for="check1">2번 게시글</label>
          </td> -->
          <td>{{ post.id }}</td>
          <td>{{ post.category.name }}</td>
          <td>
            <a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a>
          </td>
          <td>{{ post.writer.email }}</td>
          <td>{{ post.created_at | date:'Y-m-d' }}</td>
          <td>{{ post.views }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <!-- //게시판 리스트 -->


  <div class="board-bottom">
    <!-- 페이지 -->
    <div class="pagination">
      <a href="?page=1"><img src="{% static 'img/first.png' %}" alt="첫번째 페이지"></a>
      <a {% if posts.has_previous %}href="?page={{ posts.previous_page_number }}"{% endif %}>
      <img src="{% static 'img/prev.png' %}" alt="이전 페이지"></a>
      {% for page_number in pageRange %}
        <a href="?page={{ page_number }}"
        {% if page_number == posts.number %}
        class="num active"
        {% else %}
        class="num"
        {% endif %}
      >{{ page_number }}</a>
      {% endfor %}
      <a {% if posts.has_next %} href="?page={{ posts.next_page_number }}" {% endif %}>
      <img src="{% static 'img/next.png' %}" alt="다음 페이지"></a>
      <a href="?page={{ lastPage }}"><img src="{% static 'img/last.png' %}" alt="마지막 페이지"></a>
    </div>
    <!-- //페이지 -->
    <div class="btn-group">
      <!-- <button class="btn">선택삭제</button> -->
      {% if request.user.is_authenticated == True %}
        <a href="{% url 'blog:write' %}" class="btn">글쓰기</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js %}
  <script>
    const searchForm = document.getElementById("search-form")
    searchForm.addEventListener('submit', (e) => {
      e.preventDefault();
      const data = new FormData(e.target);
      window.location.replace(`/blog/search/${data.get("category")}&${data.get("search")}`)
    })
  </script>
{% endblock %}