blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'),
    # 글 상세 조회
    path("<int:pk>/", views.DetailView.as_view(), name='detail'),
    # 글 작성
    path("write/", views.Write.as_view(), name='write'),
    # 글 수정
    path("edit/<int:pk>/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("delete/<int:pk>/", views.Delete.as_view(), name='delete'),
    # 검색
    path("search/<str:tag>/", views.Search.as_view(), name='search'),
]

djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.IndexMain.as_view()),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path("register/", views.Registration.as_view(), name='register'),
    path("login/", views.Login.as_view(), name='login'),
    path("logout/", views.Logout.as_view(), name='logout'),
]

templates/base.html
{% load i18n %}
<!DOCTYPE html>
{% load static %}
<html lang="ko-KR">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="{% static 'css/common.css' %}">
  {% block static %}
  {% endblock %}
</head>

<body>
  <!-- header -->
  <div class="header">
    <h1><a href="{% url 'blog:list' %}">Blog</a></h1>
    <div class="header-click">
      <!-- <a href="chat.html">채팅</a> -->
      {% if request.user.is_authenticated == True %}
        {{ request.user.email }}
      {% else %}
        <a href="{% url 'user:login' %}">로그인</a>
        <a href="{% url 'user:register' %}">회원가입</a>
      {% endif %}
      {% if request.user.is_authenticated == True %}
        <a href="{% url 'user:logout' %}">로그아웃</a>
      {% endif%}
    </div>
  </div>
  <!-- // header -->

  <div class="main">
    {% block content %}
    {% endblock %}
  </div>
  {% block js %}
  {% endblock %}
  <!-- footer -->
  <p class="footer">Copyright 2023. Chilli All rights reserved.</p>
  <!-- //footer -->
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
  <link rel="stylesheet" href="{% static 'css/table.css' %}">
  <link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock %}
{% block content %}
  <a href="{% url 'blog:list' %}">블로그 입장하기</a>
{% endblock %}